import { useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import {Hero, Faq, LetsStart, BusinessAccount} from '@/components'
import { useTranslation } from 'react-i18next'
import i18n from 'i18next';

export default function Home() {
  const [language, setLanguage] = useState('en')
  const { t } = useTranslation()
  const handleLanguageChange = (newLanguage) => {
    setLanguage(newLanguage)
    i18n.changeLanguage(newLanguage)
  }
  return (
    <>
      <Head>
        <title>Gotimate</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Hero />
        <Faq />
        <LetsStart />
        <BusinessAccount/>
      
    </>
  )
}
